---
apiVersion: v1
kind: Pod
metadata:
  name: interactive
  labels:
    app: interactive
spec:
  containers:
  - name: interactive
    image: gcr.io/$project/ocropy

    command: ["/bin/bash"]
    args:
    - "-c"
    - |
      daemon -n vnc -- tightvncserver -geometry 1600x900 :99
      export DISPLAY=:99
      sleep 1000000
    resources:
      requests:
      limits:
        nvidia.com/gpu: "1"
        cpu: "6"
        memory: "8192Mi"
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-k80

