---
apiVersion: v1
kind: Pod
metadata:
  name: ocropy-interactive
  labels:
    app: ocropy-interactive
spec:
  containers:
  - name: ocropy-interactive
    image: gcr.io/research-191823/ocropy
    command: ["/usr/local/bin/runcmd"]
    args:
    - sleep
    - "1000000"
    resources:
      requests:
      limits:
        nvidia.com/gpu: "1"
        cpu: "8"
        memory: "16384Mi"
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-p100
